### ISSUE TITLE
Water Balance not displaying correctly

### ISSUE THREAD

**Issue by PranutiChoppakatla** [atreebangalore/jaltol#1]
**Describe the bug**
For the given shapefile the result runoff for any given shape is 0mm and other data is not available.

**To Reproduce**
If using a custom shapefile please upload ZIP of the same to project google drive folder GISLayers and add link below.
Link: https://drive.google.com/drive/u/0/folders/1Qg44GPY4EYOqmY_pPCbvrAB9w0-iHPw3

1. Area of Interest is a custom shapefile.
2. Selected one particular shape from the custom shapefile.
3. Run the water balance for 2015
4. 

**Expected behavior**
Expected the water balance where we have data for all the factors. here we have 0 runoff for any given shape.

**Screenshots**
![water_balance](https://user-images.githubusercontent.com/99713334/154208071-a79a2250-0ef3-46ae-882f-32754e58dcd4.png)

**Desktop (please complete the following information):**
 - OS Name and Version : [e.g. Windows 10, Ubuntu 20.0] Windows 10
 - QGIS Version:  [e.g. 3.16] 3.16.10

**Additional context**
No

**Comment by atreebangalore** [comment]
error identified as:
Image.reduceRegion: The 'geometry' parameter is at least partly outside the selected projection's area of validity.
needs more debugging to resolve

**Comment by atreebangalore** [comment]
used get-selected-geometry.py to identify shp file's geometry. 
It seems the shp was created in a different projection than EPSG:4326
![image](https://user-images.githubusercontent.com/70751764/154431182-da231def-c17f-4f36-97ec-febf79259b6c.png)
will need to identify and assign the file to the correct projection for this file to work.
what is it's original source?

**Comment by atreebangalore** [comment]
correct projection is EPSG:32643, after reprojecting the shp file to this it works correctly.
![water_balance](https://user-images.githubusercontent.com/70751764/154435549-128df947-4c26-4344-aadc-66262367e9b4.png)

please verify @PranutiChoppakatla
